<x-layouts.app title="BIS Hub | Rute Bus Kota">
    <section class="relative overflow-hidden bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950 text-white">
        <div class="absolute inset-0 opacity-25" style="background-image:radial-gradient(#38bdf8 1px,transparent 1px);background-size:26px 26px"></div>
        <div class="relative max-w-6xl mx-auto px-5 py-16 md:py-24 grid lg:grid-cols-[1.05fr_.95fr] gap-12 items-center">
            <div data-aos="fade-right">
                <p class="inline-flex items-center rounded-full bg-blue-400/15 border border-blue-300/30 px-3 py-1 text-xs font-bold tracking-widest text-blue-200">DINAS PERHUBUNGAN</p>
                <h1 class="mt-5 text-4xl md:text-6xl font-black leading-[1.08] tracking-tight">Mau ke mana<br><span class="text-sky-300">hari ini?</span></h1>
                <p class="mt-5 max-w-lg text-lg leading-relaxed text-slate-300">Cari jalur bus, cek halte yang dilewati, dan rencanakan perjalanan dengan lebih tenang.</p>
                <div class="mt-8 flex items-center gap-5 text-sm text-slate-300"><span class="flex items-center gap-2"><b class="text-white text-lg">{{ $busCount }}</b> jalur aktif</span><span class="w-px h-5 bg-slate-600"></span><span>Informasi rute terkini</span></div>
            </div>
            <form action="{{ route('search') }}" class="rounded-3xl bg-white p-5 md:p-7 text-slate-900 shadow-2xl shadow-slate-950/40" data-aos="fade-left">
                <div class="flex items-center justify-between mb-6"><div><h2 class="font-black text-xl">Rencanakan perjalanan</h2><p class="text-sm text-slate-500 mt-1">Pilih halte keberangkatan dan tujuan Anda.</p></div><span class="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600">⌁</span></div>
                <div class="space-y-3">
                    <label class="block"><span class="mb-1.5 block text-xs font-bold text-slate-600">LOKASI AWAL</span><span class="relative block"><svg class="absolute left-4 top-1/2 -translate-y-1/2 text-emerald-500" width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg><select name="origin" class="h-14 w-full appearance-none rounded-xl border border-[#D1D5DB] bg-white pl-12 pr-10 text-sm font-medium outline-none transition focus:border-[#2563EB] focus:ring-4 focus:ring-blue-100"><option value="">Pilih halte atau lokasi awal</option>@foreach($stops as $stop)<option value="{{ $stop->id }}">{{ $stop->name }}</option>@endforeach</select><svg class="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-slate-400" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 9 6 6 6-6"/></svg></span></label>
                    <label class="block"><span class="mb-1.5 block text-xs font-bold text-slate-600">TUJUAN</span><span class="relative block"><svg class="absolute left-4 top-1/2 -translate-y-1/2 text-orange-500" width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 22s7-5.2 7-12a7 7 0 1 0-14 0c0 6.8 7 12 7 12Z"/><circle cx="12" cy="10" r="2.5"/></svg><select name="destination" class="h-14 w-full appearance-none rounded-xl border border-[#D1D5DB] bg-white pl-12 pr-10 text-sm font-medium outline-none transition focus:border-[#2563EB] focus:ring-4 focus:ring-blue-100"><option value="">Pilih tujuan</option>@foreach($stops as $stop)<option value="{{ $stop->id }}">{{ $stop->name }}</option>@endforeach</select><svg class="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-slate-400" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 9 6 6 6-6"/></svg></span></label>
                </div>
                <button class="mt-5 flex h-14 w-full items-center justify-center gap-2 rounded-xl bg-[#2563EB] font-bold text-white shadow-lg shadow-blue-500/25 transition hover:-translate-y-0.5 hover:bg-blue-700"><span>Cari rute bus</span><span>→</span></button>
            </form>
        </div>
    </section>
    <section class="max-w-6xl mx-auto px-5 py-16">
        <div class="flex items-end justify-between gap-6"><div><p class="text-xs font-bold tracking-widest text-blue-600">INFORMASI HALTE</p><h2 class="mt-2 text-2xl font-black">Bus yang melewati halte</h2><p class="mt-2 text-slate-500">Satu halte dapat dilayani oleh beberapa jalur bus.</p></div><a href="{{ route('search') }}" class="hidden sm:block text-sm font-bold text-blue-600 hover:text-blue-800">Lihat semua rute →</a></div>
        <div class="mt-7 grid sm:grid-cols-2 lg:grid-cols-4 gap-4">@forelse($featuredStops as $stop)<a href="{{ route('stops.show',$stop) }}" class="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg" data-aos="fade-up"><div class="flex justify-between"><span class="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-lg">⌖</span><span class="text-slate-400 group-hover:text-blue-600">→</span></div><h3 class="mt-5 font-bold">{{ $stop->name }}</h3><div class="mt-3 flex flex-wrap gap-1.5">@foreach($stop->routes->pluck('bus')->unique('id') as $bus)<x-route-badge :number="$bus->corridor_number" :color="$bus->color" />@endforeach</div><p class="mt-3 text-xs text-slate-500">{{ $stop->routes->pluck('bus')->unique('id')->count() }} jalur melayani halte ini</p></a>@empty <p class="text-slate-500">Data layanan halte akan tampil setelah rute dibuat.</p>@endforelse</div>
    </section>
</x-layouts.app>
